### ISSUE TITLE
Elaborate on README's remark about lpSolveAPI and ROI

### ISSUE THREAD

**Issue by ramiromagno** [FlorianSchwendinger/lpSolveAPI#1]
Hi, I am new to linear programming (LP), but I started to look into the R package `Benchmarking`, which uses `lpSolveAPI` for LP, and I thought it could be nice to refactor some of the code there for my own purposes.

So you could elaborate on this comment of yours:

> The lpSolveAPI package was created by Kjell Konis, I currently maintain the package. lpSolveAPI provides an interface to lp_solve which was last updated 2016. Therefore if you don't need callbacks it is recommended to use ROI (https://cran.r-project.org/package=ROI, http://roi.r-forge.r-project.org/) instead.

In exactly what circumstances should I prefer `ROI` over `lpSolveAPI`? Given that `Benchmarking` already uses `lpSolveAPI` I would like to know if it is really worthwhile changing the code to `ROI`.

Thanks in advance!

**Comment by FlorianSchwendinger** [comment]
The last version of [lpsolve](https://sourceforge.net/projects/lpsolve/files/) is from 2016, which means lpsolve is not actively maintained.
From my perspective there is almost no reason to use lpsolve since GLPK and Cbc are also open source and work better in my experience.
In some situations (typically big problems LP and MILP) you have to use CPLEX, Gurobi or Mosek since the open source opens can't handle the problem. 
ROI has the advantage you write your code in a simple modeling language after that you can choose from many solvers for LP and MILP (all the solvers mentioned above and more).
Also if you create a package you which internally solves a LP or MILP it is sufficient if you put ROI and e.g. GPLK into the package imports. However you can easily write your package such that if the user has lets say CPLEX the user can use CPLEX for the optimization.

**Comment by ramiromagno** [comment]
I'm sold.
